// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptDmCallReducer from "./accept_dm_call_reducer";
import AcceptFriendRequestReducer from "./accept_friend_request_reducer";
import AcceptGuildInviteReducer from "./accept_guild_invite_reducer";
import AckRtcSignalReducer from "./ack_rtc_signal_reducer";
import AddDmReactionReducer from "./add_dm_reaction_reducer";
import AddReactionReducer from "./add_reaction_reducer";
import CancelFriendRequestReducer from "./cancel_friend_request_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateDmChannelReducer from "./create_dm_channel_reducer";
import CreateGuildReducer from "./create_guild_reducer";
import DeclineDmCallReducer from "./decline_dm_call_reducer";
import DeclineFriendRequestReducer from "./decline_friend_request_reducer";
import DeclineGuildInviteReducer from "./decline_guild_invite_reducer";
import DeleteChannelReducer from "./delete_channel_reducer";
import DeleteDmMessageReducer from "./delete_dm_message_reducer";
import DeleteGuildReducer from "./delete_guild_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import DeleteRtcSignalReducer from "./delete_rtc_signal_reducer";
import EditDmMessageReducer from "./edit_dm_message_reducer";
import EditMessageReducer from "./edit_message_reducer";
import InitiateDmCallReducer from "./initiate_dm_call_reducer";
import InviteMemberReducer from "./invite_member_reducer";
import JoinGuildReducer from "./join_guild_reducer";
import JoinVoiceChannelReducer from "./join_voice_channel_reducer";
import JoinVoiceDmReducer from "./join_voice_dm_reducer";
import KickMemberReducer from "./kick_member_reducer";
import LeaveDmChannelReducer from "./leave_dm_channel_reducer";
import LeaveGuildReducer from "./leave_guild_reducer";
import LeaveVoiceChannelReducer from "./leave_voice_channel_reducer";
import LoginAsUserReducer from "./login_as_user_reducer";
import RegisterUserReducer from "./register_user_reducer";
import RemoveDmReactionReducer from "./remove_dm_reaction_reducer";
import RemoveFriendReducer from "./remove_friend_reducer";
import RemoveReactionReducer from "./remove_reaction_reducer";
import SendDmMessageReducer from "./send_dm_message_reducer";
import SendDmRtcSignalReducer from "./send_dm_rtc_signal_reducer";
import SendFriendRequestReducer from "./send_friend_request_reducer";
import SendMessageReducer from "./send_message_reducer";
import SendRtcSignalReducer from "./send_rtc_signal_reducer";
import SetStatusReducer from "./set_status_reducer";
import ToggleDmReactionReducer from "./toggle_dm_reaction_reducer";
import ToggleReactionReducer from "./toggle_reaction_reducer";
import UpdateChannelReducer from "./update_channel_reducer";
import UpdateProfileReducer from "./update_profile_reducer";
import UpdateVoiceStateReducer from "./update_voice_state_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import DmCallEventRow from "./dm_call_event_table";
import DmCallRequestRow from "./dm_call_request_table";
import DmReactionRow from "./dm_reaction_table";
import GuildInviteRow from "./guild_invite_table";
import MyChannelsRow from "./my_channels_table";
import MyDmCallEventsRow from "./my_dm_call_events_table";
import MyDmChannelsRow from "./my_dm_channels_table";
import MyDmMessagesRow from "./my_dm_messages_table";
import MyDmParticipantsRow from "./my_dm_participants_table";
import MyFriendEdgesRow from "./my_friend_edges_table";
import MyFriendRequestsIncomingRow from "./my_friend_requests_incoming_table";
import MyFriendRequestsOutgoingRow from "./my_friend_requests_outgoing_table";
import MyFriendsRow from "./my_friends_table";
import MyGuildMembersRow from "./my_guild_members_table";
import MyGuildsRow from "./my_guilds_table";
import MyMessagesRow from "./my_messages_table";
import MyProfileRow from "./my_profile_table";
import MyReactionsRow from "./my_reactions_table";
import MyRtcSignalsRow from "./my_rtc_signals_table";
import MyVoiceStatesRow from "./my_voice_states_table";
import UserRow from "./user_table";
import UserPresenceRow from "./user_presence_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  dm_call_event: __table({
    name: 'dm_call_event',
    indexes: [
      { name: 'dm_call_event_by_actor_identity', algorithm: 'btree', columns: [
        'actorIdentity',
      ] },
      { name: 'dm_call_event_by_dm_channel_id', algorithm: 'btree', columns: [
        'dmChannelId',
      ] },
      { name: 'event_id', algorithm: 'btree', columns: [
        'eventId',
      ] },
    ],
    constraints: [
      { name: 'dm_call_event_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, DmCallEventRow),
  dm_call_request: __table({
    name: 'dm_call_request',
    indexes: [
      { name: 'call_id', algorithm: 'btree', columns: [
        'callId',
      ] },
      { name: 'callee_identity', algorithm: 'btree', columns: [
        'calleeIdentity',
      ] },
      { name: 'caller_identity', algorithm: 'btree', columns: [
        'callerIdentity',
      ] },
    ],
    constraints: [
      { name: 'dm_call_request_call_id_key', constraint: 'unique', columns: ['callId'] },
    ],
  }, DmCallRequestRow),
  dm_reaction: __table({
    name: 'dm_reaction',
    indexes: [
      { name: 'dm_reaction_by_dm_channel_id', algorithm: 'btree', columns: [
        'dmChannelId',
      ] },
      { name: 'dm_reaction_by_dm_message_id', algorithm: 'btree', columns: [
        'dmMessageId',
      ] },
      { name: 'dm_reaction_id', algorithm: 'btree', columns: [
        'dmReactionId',
      ] },
      { name: 'dm_reaction_by_reactor_identity', algorithm: 'btree', columns: [
        'reactorIdentity',
      ] },
    ],
    constraints: [
      { name: 'dm_reaction_dm_reaction_id_key', constraint: 'unique', columns: ['dmReactionId'] },
    ],
  }, DmReactionRow),
  guild_invite: __table({
    name: 'guild_invite',
    indexes: [
      { name: 'guild_id', algorithm: 'btree', columns: [
        'guildId',
      ] },
      { name: 'invite_id', algorithm: 'btree', columns: [
        'inviteId',
      ] },
      { name: 'invitee_identity', algorithm: 'btree', columns: [
        'inviteeIdentity',
      ] },
    ],
    constraints: [
      { name: 'guild_invite_invite_id_key', constraint: 'unique', columns: ['inviteId'] },
    ],
  }, GuildInviteRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'username', algorithm: 'btree', columns: [
        'username',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'user_username_key', constraint: 'unique', columns: ['username'] },
    ],
  }, UserRow),
  user_presence: __table({
    name: 'user_presence',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_presence_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserPresenceRow),
  my_channels: __table({
    name: 'my_channels',
    indexes: [
    ],
    constraints: [
    ],
  }, MyChannelsRow),
  my_dm_call_events: __table({
    name: 'my_dm_call_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDmCallEventsRow),
  my_dm_channels: __table({
    name: 'my_dm_channels',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDmChannelsRow),
  my_dm_messages: __table({
    name: 'my_dm_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDmMessagesRow),
  my_dm_participants: __table({
    name: 'my_dm_participants',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDmParticipantsRow),
  my_friend_edges: __table({
    name: 'my_friend_edges',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFriendEdgesRow),
  my_friend_requests_incoming: __table({
    name: 'my_friend_requests_incoming',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFriendRequestsIncomingRow),
  my_friend_requests_outgoing: __table({
    name: 'my_friend_requests_outgoing',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFriendRequestsOutgoingRow),
  my_friends: __table({
    name: 'my_friends',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFriendsRow),
  my_guild_members: __table({
    name: 'my_guild_members',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGuildMembersRow),
  my_guilds: __table({
    name: 'my_guilds',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGuildsRow),
  my_messages: __table({
    name: 'my_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMessagesRow),
  my_profile: __table({
    name: 'my_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProfileRow),
  my_reactions: __table({
    name: 'my_reactions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReactionsRow),
  my_rtc_signals: __table({
    name: 'my_rtc_signals',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRtcSignalsRow),
  my_voice_states: __table({
    name: 'my_voice_states',
    indexes: [
    ],
    constraints: [
    ],
  }, MyVoiceStatesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_dm_call", AcceptDmCallReducer),
  __reducerSchema("accept_friend_request", AcceptFriendRequestReducer),
  __reducerSchema("accept_guild_invite", AcceptGuildInviteReducer),
  __reducerSchema("ack_rtc_signal", AckRtcSignalReducer),
  __reducerSchema("add_dm_reaction", AddDmReactionReducer),
  __reducerSchema("add_reaction", AddReactionReducer),
  __reducerSchema("cancel_friend_request", CancelFriendRequestReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_dm_channel", CreateDmChannelReducer),
  __reducerSchema("create_guild", CreateGuildReducer),
  __reducerSchema("decline_dm_call", DeclineDmCallReducer),
  __reducerSchema("decline_friend_request", DeclineFriendRequestReducer),
  __reducerSchema("decline_guild_invite", DeclineGuildInviteReducer),
  __reducerSchema("delete_channel", DeleteChannelReducer),
  __reducerSchema("delete_dm_message", DeleteDmMessageReducer),
  __reducerSchema("delete_guild", DeleteGuildReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("delete_rtc_signal", DeleteRtcSignalReducer),
  __reducerSchema("edit_dm_message", EditDmMessageReducer),
  __reducerSchema("edit_message", EditMessageReducer),
  __reducerSchema("initiate_dm_call", InitiateDmCallReducer),
  __reducerSchema("invite_member", InviteMemberReducer),
  __reducerSchema("join_guild", JoinGuildReducer),
  __reducerSchema("join_voice_channel", JoinVoiceChannelReducer),
  __reducerSchema("join_voice_dm", JoinVoiceDmReducer),
  __reducerSchema("kick_member", KickMemberReducer),
  __reducerSchema("leave_dm_channel", LeaveDmChannelReducer),
  __reducerSchema("leave_guild", LeaveGuildReducer),
  __reducerSchema("leave_voice_channel", LeaveVoiceChannelReducer),
  __reducerSchema("login_as_user", LoginAsUserReducer),
  __reducerSchema("register_user", RegisterUserReducer),
  __reducerSchema("remove_dm_reaction", RemoveDmReactionReducer),
  __reducerSchema("remove_friend", RemoveFriendReducer),
  __reducerSchema("remove_reaction", RemoveReactionReducer),
  __reducerSchema("send_dm_message", SendDmMessageReducer),
  __reducerSchema("send_dm_rtc_signal", SendDmRtcSignalReducer),
  __reducerSchema("send_friend_request", SendFriendRequestReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("send_rtc_signal", SendRtcSignalReducer),
  __reducerSchema("set_status", SetStatusReducer),
  __reducerSchema("toggle_dm_reaction", ToggleDmReactionReducer),
  __reducerSchema("toggle_reaction", ToggleReactionReducer),
  __reducerSchema("update_channel", UpdateChannelReducer),
  __reducerSchema("update_profile", UpdateProfileReducer),
  __reducerSchema("update_voice_state", UpdateVoiceStateReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

