// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  dmParticipantId: __t.u64().name("dm_participant_id"),
  dmChannelId: __t.u64().name("dm_channel_id"),
  identity: __t.identity(),
  joinedAt: __t.timestamp().name("joined_at"),
});
