// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  friendId: __t.u64().name("friend_id"),
  identityLow: __t.identity().name("identity_low"),
  identityHigh: __t.identity().name("identity_high"),
  friendshipKey: __t.string().name("friendship_key"),
  createdAt: __t.timestamp().name("created_at"),
});
