// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  friendRequestId: __t.u64().name("friend_request_id"),
  senderIdentity: __t.identity().name("sender_identity"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  requestKey: __t.string().name("request_key"),
  createdAt: __t.timestamp().name("created_at"),
});
