// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MemberRole,
} from "./types";


export default __t.row({
  id: __t.u64(),
  guildId: __t.u64().name("guild_id"),
  identity: __t.identity(),
  nickname: __t.option(__t.string()),
  get role() {
    return MemberRole;
  },
  joinedAt: __t.timestamp().name("joined_at"),
});
