// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  dmChannelId: __t.u64().name("dm_channel_id"),
  actorIdentity: __t.identity().name("actor_identity"),
  eventType: __t.string().name("event_type"),
  createdAt: __t.timestamp().name("created_at"),
  durationSeconds: __t.option(__t.u64()).name("duration_seconds"),
});
