// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ChannelType,
} from "./types";


export default __t.row({
  channelId: __t.u64().name("channel_id"),
  guildId: __t.u64().name("guild_id"),
  categoryId: __t.option(__t.u64()).name("category_id"),
  name: __t.string(),
  get channelType() {
    return ChannelType.name("channel_type");
  },
  position: __t.u32(),
  topic: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
});
