// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  dmMessageId: __t.u64().name("dm_message_id"),
  dmChannelId: __t.u64().name("dm_channel_id"),
  authorIdentity: __t.identity().name("author_identity"),
  content: __t.string(),
  sentAt: __t.timestamp().name("sent_at"),
  editedAt: __t.option(__t.timestamp()).name("edited_at"),
  isDeleted: __t.bool().name("is_deleted"),
  replyTo: __t.option(__t.u64()).name("reply_to"),
});
