// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RtcSignalType,
} from "./types";


export default __t.row({
  signalId: __t.u64().name("signal_id"),
  guildId: __t.u64().name("guild_id"),
  channelId: __t.u64().name("channel_id"),
  senderIdentity: __t.identity().name("sender_identity"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  get signalType() {
    return RtcSignalType.name("signal_type");
  },
  payload: __t.string(),
  sentAt: __t.timestamp().name("sent_at"),
});
