// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity(),
  guildId: __t.u64().name("guild_id"),
  channelId: __t.u64().name("channel_id"),
  isMuted: __t.bool().name("is_muted"),
  isDeafened: __t.bool().name("is_deafened"),
  isStreaming: __t.bool().name("is_streaming"),
  joinedAt: __t.timestamp().name("joined_at"),
});
