// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  RtcSignalType,
} from "./types";

export default {
  dmChannelId: __t.u64(),
  recipientIdentity: __t.identity(),
  get signalType() {
    return RtcSignalType;
  },
  payload: __t.string(),
};
