// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Channel = __t.object("Channel", {
  channelId: __t.u64(),
  guildId: __t.u64(),
  categoryId: __t.option(__t.u64()),
  name: __t.string(),
  get channelType() {
    return ChannelType;
  },
  position: __t.u32(),
  topic: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelLayoutItem = __t.object("ChannelLayoutItem", {
  channelId: __t.u64(),
  categoryId: __t.option(__t.u64()),
  position: __t.u32(),
});
export type ChannelLayoutItem = __Infer<typeof ChannelLayoutItem>;

// The tagged union or sum type for the algebraic type `ChannelType`.
export const ChannelType = __t.enum("ChannelType", {
  Category: __t.unit(),
  Text: __t.unit(),
  Voice: __t.unit(),
  Announcement: __t.unit(),
});
export type ChannelType = __Infer<typeof ChannelType>;

export const ChannelTyping = __t.object("ChannelTyping", {
  typingKey: __t.string(),
  channelId: __t.u64(),
  identity: __t.identity(),
  expiresAt: __t.timestamp(),
});
export type ChannelTyping = __Infer<typeof ChannelTyping>;

export const DmCallEvent = __t.object("DmCallEvent", {
  eventId: __t.u64(),
  dmChannelId: __t.u64(),
  actorIdentity: __t.identity(),
  eventType: __t.string(),
  createdAt: __t.timestamp(),
  durationSeconds: __t.option(__t.u64()),
});
export type DmCallEvent = __Infer<typeof DmCallEvent>;

export const DmCallRequest = __t.object("DmCallRequest", {
  callId: __t.u64(),
  dmChannelId: __t.u64(),
  callerIdentity: __t.identity(),
  calleeIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type DmCallRequest = __Infer<typeof DmCallRequest>;

export const DmChannel = __t.object("DmChannel", {
  dmChannelId: __t.u64(),
  createdByIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type DmChannel = __Infer<typeof DmChannel>;

export const DmMessage = __t.object("DmMessage", {
  dmMessageId: __t.u64(),
  dmChannelId: __t.u64(),
  authorIdentity: __t.identity(),
  content: __t.string(),
  sentAt: __t.timestamp(),
  editedAt: __t.option(__t.timestamp()),
  isDeleted: __t.bool(),
  replyTo: __t.option(__t.u64()),
});
export type DmMessage = __Infer<typeof DmMessage>;

export const DmParticipant = __t.object("DmParticipant", {
  dmParticipantId: __t.u64(),
  dmChannelId: __t.u64(),
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
  lastReadMessageId: __t.option(__t.u64()),
});
export type DmParticipant = __Infer<typeof DmParticipant>;

export const DmReaction = __t.object("DmReaction", {
  dmReactionId: __t.u64(),
  dmMessageId: __t.u64(),
  dmChannelId: __t.u64(),
  reactorIdentity: __t.identity(),
  emoji: __t.string(),
  reactedAt: __t.timestamp(),
});
export type DmReaction = __Infer<typeof DmReaction>;

export const DmTyping = __t.object("DmTyping", {
  typingKey: __t.string(),
  dmChannelId: __t.u64(),
  identity: __t.identity(),
  expiresAt: __t.timestamp(),
});
export type DmTyping = __Infer<typeof DmTyping>;

export const Friend = __t.object("Friend", {
  friendId: __t.u64(),
  identityLow: __t.identity(),
  identityHigh: __t.identity(),
  friendshipKey: __t.string(),
  createdAt: __t.timestamp(),
});
export type Friend = __Infer<typeof Friend>;

export const FriendRequest = __t.object("FriendRequest", {
  friendRequestId: __t.u64(),
  senderIdentity: __t.identity(),
  recipientIdentity: __t.identity(),
  requestKey: __t.string(),
  createdAt: __t.timestamp(),
});
export type FriendRequest = __Infer<typeof FriendRequest>;

export const Guild = __t.object("Guild", {
  guildId: __t.u64(),
  name: __t.string(),
  avatarBytes: __t.option(__t.byteArray()),
  bio: __t.option(__t.string()),
  ownerIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Guild = __Infer<typeof Guild>;

export const GuildInvite = __t.object("GuildInvite", {
  inviteId: __t.u64(),
  guildId: __t.u64(),
  inviterIdentity: __t.identity(),
  inviteeIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type GuildInvite = __Infer<typeof GuildInvite>;

export const GuildMember = __t.object("GuildMember", {
  id: __t.u64(),
  guildId: __t.u64(),
  identity: __t.identity(),
  nickname: __t.option(__t.string()),
  get role() {
    return MemberRole;
  },
  joinedAt: __t.timestamp(),
});
export type GuildMember = __Infer<typeof GuildMember>;

// The tagged union or sum type for the algebraic type `MemberRole`.
export const MemberRole = __t.enum("MemberRole", {
  Member: __t.unit(),
  Moderator: __t.unit(),
  Admin: __t.unit(),
  Owner: __t.unit(),
});
export type MemberRole = __Infer<typeof MemberRole>;

export const Message = __t.object("Message", {
  messageId: __t.u64(),
  channelId: __t.u64(),
  authorIdentity: __t.identity(),
  content: __t.string(),
  sentAt: __t.timestamp(),
  editedAt: __t.option(__t.timestamp()),
  isDeleted: __t.bool(),
  replyTo: __t.option(__t.u64()),
});
export type Message = __Infer<typeof Message>;

export const PresenceOfflineJob = __t.object("PresenceOfflineJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
  expectedGeneration: __t.u64(),
});
export type PresenceOfflineJob = __Infer<typeof PresenceOfflineJob>;

export const PresenceState = __t.object("PresenceState", {
  identity: __t.identity(),
  onlineSessionCount: __t.u32(),
  get statusBeforeDisconnect() {
    return __t.option(UserStatus);
  },
  generation: __t.u64(),
});
export type PresenceState = __Infer<typeof PresenceState>;

export const Reaction = __t.object("Reaction", {
  reactionId: __t.u64(),
  messageId: __t.u64(),
  channelId: __t.u64(),
  reactorIdentity: __t.identity(),
  emoji: __t.string(),
  reactedAt: __t.timestamp(),
});
export type Reaction = __Infer<typeof Reaction>;

export const RtcSignal = __t.object("RtcSignal", {
  signalId: __t.u64(),
  guildId: __t.u64(),
  channelId: __t.u64(),
  senderIdentity: __t.identity(),
  recipientIdentity: __t.identity(),
  get signalType() {
    return RtcSignalType;
  },
  payload: __t.string(),
  sentAt: __t.timestamp(),
});
export type RtcSignal = __Infer<typeof RtcSignal>;

// The tagged union or sum type for the algebraic type `RtcSignalType`.
export const RtcSignalType = __t.enum("RtcSignalType", {
  Offer: __t.unit(),
  Answer: __t.unit(),
  IceCandidate: __t.unit(),
  Bye: __t.unit(),
});
export type RtcSignalType = __Infer<typeof RtcSignalType>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  displayName: __t.string(),
  avatarBytes: __t.option(__t.byteArray()),
  get status() {
    return UserStatus;
  },
  createdAt: __t.timestamp(),
  bio: __t.option(__t.string()),
  profileColor: __t.option(__t.string()),
});
export type User = __Infer<typeof User>;

export const UserPresence = __t.object("UserPresence", {
  identity: __t.identity(),
  get status() {
    return UserStatus;
  },
  changedAt: __t.timestamp(),
});
export type UserPresence = __Infer<typeof UserPresence>;

// The tagged union or sum type for the algebraic type `UserStatus`.
export const UserStatus = __t.enum("UserStatus", {
  Online: __t.unit(),
  Away: __t.unit(),
  DoNotDisturb: __t.unit(),
  Offline: __t.unit(),
});
export type UserStatus = __Infer<typeof UserStatus>;

export const VoiceState = __t.object("VoiceState", {
  identity: __t.identity(),
  guildId: __t.u64(),
  channelId: __t.u64(),
  isMuted: __t.bool(),
  isDeafened: __t.bool(),
  isStreaming: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type VoiceState = __Infer<typeof VoiceState>;

